FROM nikolaik/python-nodejs:python3.8-nodejs18
WORKDIR /app
EXPOSE 3000 8888
# Install python dependencies
COPY requirements.txt /app/
RUN pip3 install -r requirements.txt
# Extensions for nbdocs and onedark theme
RUN jupyter labextension install @jupyterlab/vega5-extension jupyterlab_onedarkpro
# Install node dependencies
COPY package.json /app/
RUN npm install
# Build Markdown files from Jupyter Notebooks
COPY . /app/
RUN nbdoc_update && nbdoc_build
